### ISSUE TITLE
Pathway curation

### ISSUE THREAD

**Issue by mschubert** [saezlab/footprints#1]
Z-scores: min 2 arrays in basal condition, average for perturbed

Format: [yaml](http://en.wikipedia.org/wiki/YAML)

``` yaml

---
id        : <pathway.accession.#>
accession : <arrayexpress accession>
platform  : <arrayexpress platform id>
pathway   : <out of set below>
cells     : <human-readable cell description>
treatment : <human-readable treatment description>
effect    : activating|inhibiting
hours     : <int> number of hours treatment

control   :
    - <list of control arrays>
perturbed :
    - <list of perturbed arrays>
...
```

Pathways included:
- [x] EGFR
- [x] MAPK
- [x] PI3K
- [x] H2O2
- [x] Hypoxia
- [x] Trail
- [x] p53
- [x] TNFa
- [x] NFkB
- [x] VEGF
- [x] TGFb
- [ ] Insulin
- [ ] IL1
- [ ] RAR
- [ ] notch
- [ ] PPAR
- [ ] Estrogen
- [x] JAK-STAT
- [ ] Wnt
- [ ] acidosis ?
- [ ] senescence ?
- [ ] starvataion ?
